# Pre-commit hooks configuration for iShop project
repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.11
        args: [--profile=black, --line-length=88]
        files: \.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language_version: python3.11
        args: [--max-line-length=88, --extend-ignore=E203,E266,E501,W503]
        files: \.py$

  # Frontend formatting and linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^6.7.4"
          - "@typescript-eslint/parser@^6.7.4"
          - "eslint-plugin-react@^7.33.2"
          - "eslint-plugin-react-hooks@^4.6.0"
          - "eslint-plugin-react-refresh@^0.4.4"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        exclude: |
          (?x)^(
              \.vscode/|
              node_modules/|
              dist/|
              build/|
              coverage/|
              \.next/|
              \.nuxt/|
              \.output/|
              \.vercel/|
              \.netlify/|
              \.cache/|
              public/|
              static/
          )

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-yaml
        args: [--multi]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-docstring-first
        files: \.py$
      - id: debug-statements
        files: \.py$
      - id: name-tests-test
        files: tests/.+\.py$
        args: [--pytest-test-first]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
              \.secrets\.baseline|
              poetry\.lock|
              package-lock\.json|
              yarn\.lock|
              \.env\.example
          )$

  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false