[providers.python]
version = "3.11"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_NO_MUSL = "1"
