[phases.setup]
providers = ["python"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHON_VERSION = "3.11"
NIXPACKS_NO_MUSL = "1"

[providers.python]
version = "3.11"
